// app/src/components/admin/FinishVote.svelte
<script>
    let contractvar
    let accountsvar

    const endVoting = () => {
        contractvar.methods.endVotingSession().send({from: accountsvar[0]})
    }
</script>

<div class="container py-2">
    <div class="row justify-content-center">
        <button class="btn btn-primary" on:click={endVoting}>End voting</button>
    </div>
</div>

// app/src/components/admin/FinishVote.vue
<script setup lang="ts">
const endVoting = () => {

}
</script>

<template>
    <div class="container">
        <div class="row justify-content-center">
            <button class="btn btn-primary" v-on:click="endVoting">End voting</button>
        </div>
    </div>
</template>

<style scoped>

</style>
