// app/src/components/admin/ShowProposal.vue
<script setup lang="ts">
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap/dist/js/bootstrap.js";

const finishProposal = () => {

}

const emit = defineEmits<{
    (e:'endProposal'):void
}>()
</script>

<template>
    <div class="container">
        <div class="row my-5">
            <ul class="list-group">
                <li class="list-group-item">test1</li>
                <li class="list-group-item">test2</li>
            </ul>
        </div>
        <div class="row justify-content-center">
            <button class="btn btn-primary" v-on:click="finishProposal">Finish proposals</button>
        </div>
    </div>
</template>

<style scoped>

</style>

// app/src/components/admin/ShowProposal.svelte
<script>
    let contractvar
    let accountsvar

    const proposals = []
    let item

    contractvar.methods.getProposalsLength().call((err, res) => {
        for (let i = 0; i < res; i++) {
            contractvar.methods.proposals(i).call((err1, res1) => {
                proposals.value.push(res1)
            })
        }
    })

    const endProposal = () => {
        contractvar.value.methods.endProposalsRegistration().send({from: accountsvar.value[0]})
    }
</script>

<div class="container py-2">
    <div class="row my-4">
        <table class="table" id="myTable">
            {#each item as proposals}
                <tr for="item in proposals">
                    <th style="width: 80%;" scope="row">{ item.description }</th>
                </tr>
            {/each}
        </table>
    </div>
    <div class="row justify-content-center">
        <button class="btn btn-primary" on:click="endProposal()">Finish proposals</button>
    </div>
</div>
