// app/src/components/admin/StartVote.svelte
<script>
    export let contractvar
    export let accountsvar

    const startVote = () => {
        contractvar.methods.startVotingSession().send({from: accountsvar[0]})
    }
</script>

<div class="container py-2">
    <div class="row justify-content-center">
        <button class="btn btn-primary" on:click={startVote}>Start vote</button>
    </div>
</div>

// app/src/components/admin/StartVote.vue
<script setup lang="ts">
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap/dist/js/bootstrap.js";

const startVote = () => {

}
</script>

<template>
    <div class="container">
        <div class="row justify-content-center">
            <button class="btn btn-primary" v-on:click="startVote">Start vote</button>
        </div>
    </div>
</template>

<style scoped>

</style>
