// app/src/components/admin/TallyVote.svelte
<script>
    let contractvar
    let accountsvar

    const tallyVote = () => {
        contractvar.methods.tallyVotes().send({from: accountsvar[0]})
    }
</script>

<div class="container py-2">
    <div class="row justify-content-center">
        <button class="btn btn-primary" on:click={tallyVote}>Tally votes</button>
    </div>
</div>

// app/src/components/admin/TallyVote.vue
<script setup lang="ts">
const tallyVote = () => {

}
</script>

<template>
    <div class="container">
        <div class="row justify-content-center">
            <button class="btn btn-primary" v-on:click="tallyVote">Tally votes</button>
        </div>
    </div>
</template>

<style scoped>

</style>
